# This file was generated by GoReleaser. DO NOT EDIT.
class Gogitmoji < Formula
  desc "gogitmoji helps you write git commit messages containing gitmoji!"
  homepage "https://github.com/oorrwullie/gogitmoji"
  version "0.0.1"
  bottle :unneeded

  if Hardware::CPU.intel?
    if OS.mac?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.1/gogitmoji_0.0.1_macOS_x86_64.tar.gz"
      sha256 "a7c05b6cda760fd91043af3130772e8c32382b2dceb69849f83face790e411d1"
    elsif OS.linux?
        url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.1/gogitmoji_0.0.1_Linux_x86_64.tar.gz"
        sha256 "0d43ef9c863fee7cc8f5eaf317e153c3bb1d5581ed805f2af3d9e8755b1fba74"
    end
  elsif Hardware::CPU.arm?
    if OS.mac?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.1/gogitmoji_0.0.1_macOS_arm.tar.gz"
      sha256 "a7c05b6cda760fd91043af3130772e8c32382b2dceb69849f83face790e411d1"
    end
  end

  def install
    bin.install "gitmoji"
  end
end
