# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogitmoji < Formula
  desc "gogitmoji helps you write git commit messages containing gitmoji!"
  homepage "https://github.com/oorrwullie/gogitmoji"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_darwin_arm64.tar.gz"
      sha256 "24b9b8230e2d491b2d1e35b966941eb888710c8faeb2e7e77f847ff999c3d627"

      def install
        bin.install "gitmoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_darwin_amd64.tar.gz"
      sha256 "33d934b81c29606489dd9c423a701d891895066bb2e268ccb64aaf82d6a9ebc8"

      def install
        bin.install "gitmoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_linux_arm64.tar.gz"
      sha256 "bd6efe2d60cd22df4085202817e7bcd0b68ed900cf09809fccb2a86774ba18d7"

      def install
        bin.install "gitmoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_linux_amd64.tar.gz"
      sha256 "628a362d697c2b3e9bd60f7326b24b3e9b5234006c39eaaaa2dea5f666ae8961"

      def install
        bin.install "gitmoji"
      end
    end
  end
end
