# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogitmoji < Formula
  desc "gogitmoji helps you write git commit messages containing gitmoji!"
  homepage "https://github.com/oorrwullie/gogitmoji"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_darwin_arm64.tar.gz"
      sha256 "eb084cc8784160f074023a710a6ae46b68fa5765ed6bb4dc4f25c65b103a0824"

      def install
        bin.install "gitmoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_darwin_amd64.tar.gz"
      sha256 "5b1977dc52c226450970bf60001d2c86bc4d78c840474843b6cfaa7a142aeaef"

      def install
        bin.install "gitmoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_linux_arm64.tar.gz"
      sha256 "d10bd61c7b987532fb5f33a930fd2c5d22393d14f0f6ba3f4c70979fd2ca71db"

      def install
        bin.install "gitmoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oorrwullie/gogitmoji/releases/download/v0.0.2/gogitmoji_0.0.2_linux_amd64.tar.gz"
      sha256 "66922e2788f8deac32898870703e09d74490cdf005bd22080015b0f800c53878"

      def install
        bin.install "gitmoji"
      end
    end
  end
end
